source /home/manager/zabbix_server_intall/lib/create_mysql_files_grant_zabbix_user.sh.sh
source /home/manager/zabbix_server_intall/lib/create_mysql_files_init_mysql.sh.sh
source /home/manager/zabbix_server_intall/lib/create_mysql_tasks_main.yml.sh
source /home/manager/zabbix_server_intall/lib/create_nginx_files_init_nginx.sh.sh
source /home/manager/zabbix_server_intall/lib/create_nginx_tasks_main.yml.sh
source /home/manager/zabbix_server_intall/lib/create_nginx_templates_nginx.conf.sh
source /home/manager/zabbix_server_intall/lib/create_nginx_templates_nginx.service.sh
source /home/manager/zabbix_server_intall/lib/create_nginx_templates_zabbix.conf.sh
source /home/manager/zabbix_server_intall/lib/create_php_files_init_php.sh.sh
source /home/manager/zabbix_server_intall/lib/create_php_files_php_support_zabbix.sh.sh
source /home/manager/zabbix_server_intall/lib/create_php_handlers_main.yml.sh
source /home/manager/zabbix_server_intall/lib/create_php_tasks_main.yml.sh
source /home/manager/zabbix_server_intall/lib/create_php_templates_php-fpm.service.sh
source /home/manager/zabbix_server_intall/lib/create_zabbix_files_init_zabbix.sh.sh
source /home/manager/zabbix_server_intall/lib/create_zabbix_tasks_main.yml.sh
source /home/manager/zabbix_server_intall/lib/create_zabbix_templates_zabbix_server.conf.sh
source /home/manager/zabbix_server_intall/lib/create_zabbix_templates_zabbix-server.service.sh
